name: NoSmoking
version: @version@-@apiversion@
description: NoSmoking
authors: [ DartPower, fromgate ]
website: https://github.com/dptmc/NoSmoking
main: io.dpteam.NoSmoking.Main
api-version: 1.13

commands:
   smoke:
      description: No smoking plugin configuration command
      usage: 
           /smoke help